#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

# A script which starts Cassandra daemon and enables password authentication
#
# References
#   http://cassandra.apache.org/doc/4.0/operating/security.html#authentication

# Update Configurations file
sed -i -r 's/^(# )?(authenticator:).*/\2 PasswordAuthenticator/' /etc/cassandra/cassandra.yaml

# Initialize username
USER_NAME="${USER_NAME:-femiwiki}"

# Create random passwords with CSPRNG
ADMIN_PASSWORD="$(base64 /dev/urandom|tr -d /+|head -c35 || true)"
if [ -z "${DEV_PASSWORD:-}" ]; then
  USER_PASSWORD="$(base64 /dev/urandom|tr -d /+|head -c35 || true)"
else
  USER_PASSWORD=${DEV_PASSWORD}
fi

enable-authentication() {
  # Wait until cassandra is ready
  until cqlsh -u cassandra -p cassandra -e "SHOW HOST;" ; do
    sleep 2;
  done

  echo 'Creating a new keyspace with a different name and a different replication factor'
  # References:
  #   http://cassandra.apache.org/doc/4.0/cql/ddl.html#create-keyspace
  #   http://cassandra.apache.org/doc/4.0/operating/security.html#enabling-password-authentication
  cqlsh -u cassandra -p cassandra -e "CREATE KEYSPACE femiwiki \
                                        WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1' : 3, 'DC2' : 3}"

  echo 'Creating new superuser "admin" with arbitrary password'
  cqlsh -k femiwiki -u cassandra -p cassandra -e "CREATE ROLE admin WITH SUPERUSER = true AND LOGIN = true AND PASSWORD = '${ADMIN_PASSWORD}';"

  echo 'Disabling default superuser'
  cqlsh -k femiwiki -u admin -p "$ADMIN_PASSWORD" -e "ALTER ROLE cassandra WITH SUPERUSER = false AND LOGIN = false;"

  echo 'Creating a new user who cannot access system table'
  cqlsh -k femiwiki -u admin -p "$ADMIN_PASSWORD" -e "CREATE ROLE '${USER_NAME}' WITH LOGIN = true AND PASSWORD = '${USER_PASSWORD}';"

  # Print passwords
  echo "Generated admin(superuser)'s password: ${ADMIN_PASSWORD}"
  echo "Generated ${USER_NAME}'s password: ${USER_PASSWORD}"
}

# Keep trying to activate password authentication until it succeeds...
enable-authentication &
# Start Cassandra in the foreground
docker-entrypoint.sh cassandra -f
